services:
  stats-server:
    build: ./stats-server
    ports:
    - 9090:9090
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
      TZ: Europe/Moscow
    depends_on:
      stats-db:
        condition: service_healthy
  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
    - 5433:5432
    volumes:
    - stats-data:/var/lib/postgresql/data
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U stats -d stats
      interval: 3s
      timeout: 3s
      retries: 10
  ewm-service:
    profiles: [main]
    build: ./ewm-service
    ports:
    - 8080:8080
    depends_on:
      ewm-db:
        condition: service_healthy
  ewm-db:
    profiles: [main]
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: ewm
    ports:
    - 5432:5432
    volumes:
    - ewm-data:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, pg_isready -U ewm -d ewm]
      interval: 3s
      timeout: 3s
      retries: 10
volumes:
  stats-data: null
  ewm-data: null
